### ISSUE TITLE
BUG: If scamper tracelb fails, we don't detect the failure.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/traceroute-caller#108]
When tracelb is run with bad parameters we see "do_scamperread_line: command not accepted" in the logs.  But we apparently don't check any status.

**Comment by laiyi-ohlsen** [comment]
@gfr10598 Is this still relevant? @SaiedKazemi

**Comment by SaiedKazemi** [comment]
@laiyi-ohlsen I am assigning this bug to myself to check if it's already correctly handled or not.  If so, will close the bug.  If not, will add code to report/handle the error.

**Comment by SaiedKazemi** [comment]
Closing this bug because `runTrace()` in `tracer/scamper.go` checks for errors and logs them, distinguishing between timeouts and other types of errors.
