### ISSUE TITLE
Scamper mode now failing in sandbox

### ISSUE THREAD

**Issue by gfr10598** [m-lab/traceroute-caller#110]
Tried out scamper mode on sandbox ndt pods.  All traces are now failing:

2021/06/27 11:35:39 scamper.go:132: Trace failed in context 0xc000294540 (error: exit status 255: scamper -I "tracelb -P icmp-echo -q 3 -W 25 -O ptr 2600:3c02:e000:185:0:242:ac11:2" -o- -O json)

**Comment by SaiedKazemi** [comment]
I have assigned this issue to myself and will look into it today.

**Comment by gfr10598** [comment]
Resolved in #111
