### ISSUE TITLE
traceroute-caller should save its own version in the output data

### ISSUE THREAD

**Issue by pboothe** [m-lab/traceroute-caller#23]
The same piece that saves the UUID should also save the server commit as represented in https://github.com/m-lab/go/blob/master/prometheusx/prom.go#L31

**Comment by yachang** [comment]
https://reviewable.io/reviews/m-lab/traceroute-caller/26

https://github.com/m-lab/traceroute-caller/releases/tag/v0.2.0 
https://github.com/m-lab/k8s-support/pull/286 
https://github.com/m-lab/k8s-support/releases/tag/v2.0.0
