### ISSUE TITLE
Traceroute-caller misses some stuff

### ISSUE THREAD

**Issue by pboothe** [m-lab/traceroute-caller#28]
In particular, not every successful NDT test has a corresponding traceroute. We should understand why this is AND/OR make it so that no connections are missed.

**Comment by pboothe** [comment]
The right fix is to add an optional connection to a unix-domain socket served by the tcp-info daemon which allows the tcp-info daemon to notify connected systems when a new connection is created.

**Comment by pboothe** [comment]
Fixed in #31

**Comment by pboothe** [comment]
Part of https://github.com/m-lab/dev-tracker/issues/500

**Comment by pboothe** [comment]
Will be fixed in the next deployment.

**Comment by mehtab11** [comment]
Fixed; closed.
