### ISSUE TITLE
ipcache does not cache results

### ISSUE THREAD

**Issue by pboothe** [m-lab/traceroute-caller#29]
As written, ipcache does not cache the results, which means that UUIDs corresponding to flows with the IP in the cache don't get any data. Instead, the system should cache the result and provide the cached result when a redundant request comes in.

It should also add a metadata field or fields to indicate that (a) the result was retrieved from the cache and (b) the UUID of the connection that initially populated the cache.

**Comment by yachang** [comment]
Fixed by #33
