### ISSUE TITLE
Open file descriptor leak

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/traceroute-caller#38]
Looking at prometheus metrics for `process_open_fds` for traceroute that there is a fd leak. See image below:

![traceroute-fdleak](https://user-images.githubusercontent.com/1085316/69265847-041a7a00-0b98-11ea-96f6-9e536e149f53.png)

After a rollout on the 16th, the fd count has steadily increased until machine reboots.

Only lga0* nodes are shown for convenience. The pattern is global.  Originally started on ~Nov 8th in staging and Nov 14th in production.

`sum by(machine, container, deployment) (process_open_fds{machine=~".*", container=~"traceroute"})`

**Comment by stephen-soltesz** [comment]
This is not yet resolved. The first two bumps are the load tests using v0.3.3 -- the steady growth _without synthetic traffic_ correlates with process count increase and goroutine counts.

<img width="828" alt="Screen Shot 2019-12-05 at 8 26 46 AM" src="https://user-images.githubusercontent.com/1085316/70239284-03a5e580-1739-11ea-818f-6b1f23f1655b.png">

**Comment by pboothe** [comment]
Well, dang.

**Comment by yachang** [comment]
Fixed by 

https://github.com/m-lab/traceroute-caller/releases/tag/v0.6.0
https://github.com/m-lab/k8s-support/pull/347
