### ISSUE TITLE
scamper is trying to run on nodes that it should not (like the master nodes)

### ISSUE THREAD

**Issue by gfr10598** [m-lab/traceroute-caller#4]
The scamper deployment, at least on staging, needs a node selector to prevent it trying to run on the k8s-prometheus node.

scamper-tcf48   1/2   CrashLoopBackOff   240    20h       10.0.0.20         k8s-prometheus

**Comment by pboothe** [comment]
Needs a `NodeSelector`

**Comment by yachang** [comment]
closed as the dup of https://github.com/m-lab/k8s-support/issues/149
