### ISSUE TITLE
Definite go routine and/or process leak 

### ISSUE THREAD

**Issue by yachang** [m-lab/traceroute-caller#50]
please check traceroute for a goroutine and possible process leak -- https://grafana.mlab-sandbox.measurementlab.net/d/hU5aYvaWz/k8s-site-overview?orgId=1&var-datasource=Platform%20Cluster%20(mlab-sandbox)&var-site=lga0t&var-node=mlab3&var-pod=ndt&from=now-24h&to=now&refresh=1m
(bottom two panels)

![Screenshot from 2019-12-05 14-01-07](https://user-images.githubusercontent.com/8365769/70265140-ca389e80-1767-11ea-8aae-aa76149683ec.png)

**Comment by stephen-soltesz** [comment]
See also https://github.com/m-lab/k8s-support/issues/345

**Comment by yachang** [comment]
I ssh into the node and docker image, observe many <defunct> zoombie process:

# ps auxw
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1 114596 21104 ?        Ssl  16:55   0:04 /traceroute-caller -prometheusx.listen-address=192.168.1.66:9992 -outputPath=/var/spool/ndt/traceroute -uuid-prefix-file=/var/loca
root        38  0.0  0.0      0     0 ?        Z    16:57   0:00 [scamper] <defunct>
root        88  0.0  0.0      0     0 ?        Z    17:01   0:00 [scamper] <defunct>
root       104  0.0  0.0      0     0 ?        Z    17:02   0:00 [scamper] <defunct>
root       179  0.0  0.0      0     0 ?        Z    17:08   0:00 [scamper] <defunct>
root       276  0.0  0.0      0     0 ?        Z    17:15   0:00 [scamper] <defunct>
root       318  0.0  0.0  18508  3568 pts/0    Ss   17:19   0:00 bash
root       359  0.0  0.0      0     0 ?        Z    17:20   0:00 [scamper] <defunct>
root       438  0.0  0.0      0     0 ?        Z    17:26   0:00 [scamper] <defunct>
root       528  0.0  0.0      0     0 ?        Z    17:33   0:00 [scamper] <defunct>
root       668  0.0  0.0      0     0 ?        Z    17:45   0:00 [scamper] <defunct>
root       686  0.0  0.0      0     0 ?        Z    17:46   0:00 [scamper] <defunct>
root       755  0.0  0.0      0     0 ?        Z    17:52   0:00 [scamper] <defunct>
root       890  0.0  0.0      0     0 ?        Z    18:03   0:00 [scamper] <defunct>
root      1000  0.0  0.0      0     0 ?        Z    18:12   0:00 [scamper] <defunct>
root      1062  0.0  0.0      0     0 ?        Z    18:17   0:00 [scamper] <defunct>
root      1124  0.0  0.0      0     0 ?        Z    18:22   0:00 [scamper] <defunct>
root      1246  0.0  0.0      0     0 ?        Z    18:32   0:00 [scamper] <defunct>
root      1274  0.0  0.0      0     0 ?        Z    18:34   0:00 [scamper] <defunct>
root      1398  0.0  0.0      0     0 ?        Z    18:44   0:00 [scamper] <defunct>
root      1472  0.0  0.0      0     0 ?        Z    18:50   0:00 [scamper] <defunct>
root      1546  0.0  0.0      0     0 ?        Z    18:56   0:00 [scamper] <defunct>
root      1580  0.0  0.0      0     0 ?        Z    18:58   0:00 [scamper] <defunct>
root      1581  0.0  0.0      0     0 ?        Z    18:58   0:00 [scamper] <defunct>
root      1588  0.0  0.0      0     0 ?        Z    18:59   0:00 [scamper] <defunct>
root      1711  0.0  0.0      0     0 ?        Z    19:09   0:00 [scamper] <defunct>
root      1790  0.0  0.0  34400  2912 pts/0    R+   19:15   0:00 ps auxw

**Comment by yachang** [comment]
More info:

scamper -I tracelb -P icmp-echo -q 3 -O ptr ::ffff:35.193.254.117 -o- -O json

Some IPv4 address was converted to wrong IPv6 format and might cause the defunct processs

**Comment by yachang** [comment]
This incorrect IP "::ffff:35.193.254.117" is generated by ss, not by tcp-info, according to log info.

**Comment by pboothe** [comment]
We should make it so that the ss IPs are just as valid as the tcpinfo eventsocket IPs.

**Comment by yachang** [comment]
The sandbox version seems fixed the pid leak:

![Screenshot from 2020-01-06 09-40-15](https://user-images.githubusercontent.com/8365769/71824942-ab7c3f00-3068-11ea-9376-a071f1f2f603.png)

**Comment by yachang** [comment]
https://github.com/m-lab/traceroute-caller/releases/tag/v0.6.0

https://github.com/m-lab/k8s-support/pull/347

This will fix the pid leak in staging

**Comment by yachang** [comment]
deployed to prod, and verified for problem solved.
