### ISSUE TITLE
scamper.go:86: Scamper exited with error: signal: segmentation fault

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/traceroute-caller#52]
The frequency of scamper segfaults in staging is still very high. The consequence of this is the restart of traceroute container. The restarts result in a noisy summary of available containers relative to pre-release of v0.3.3. That alone might be okay but about 25% of the host containers not monitorable, suggesting the highest rate of segfaults in the host deployment.

![traceroute-host](https://user-images.githubusercontent.com/1085316/70330833-53091600-180c-11ea-9ce8-b7d6f4524553.png)

**Comment by pboothe** [comment]
Partially addressed in #51 and #54

**Comment by yachang** [comment]
dup of #36
